### ISSUE TITLE
An option to disable/enable the addon in certain places

### ISSUE THREAD

**Issue by Alino** [RagedUnicorn/wow-bcc-pvpwarn#1]
I am missing an option to disable the addon in cities like Shattrath, because combat is not possible in this city, but warnings are being triggered here.

Also it would be nice option to enable the warnings only in Arenas. And a sub-option to enable outside of arenas if you enter combat.

**Comment by RagedUnicorn** [comment]
Hi @Alino 

Thanks for your input. This was implement in a form with the newest 2.1.0 release. You now have a new configuration option to enable or disable certain zones. By default only Shattrath is deactivated.

Cheers
RagedUnicorn
